### ISSUE TITLE
请尊重版权

### ISSUE THREAD

**Issue by ITJesse** [XBPIG/office_line#1]
首先，我的代码是使用GPLv2发布，你必须同样使用GPLv2证书，不可发布为MIT
其次，在copyright.html中的部分内容由于你的表达失误会对大家造成误解，请删除
并对已经造成的误解形成有效的解释

你的最佳做法是fork我的仓库，而不是这样重新新建仓库，这是不可取的。
或许你不知道fork是什么意思，那么我建议你去重新学习下git

**Comment by zhoubenbentime** [comment]
首先、你可以去核实每一行代码，如果使用了你的核心代码，我会尽快删除。
第二、每一个新建的文件，软件自动加上版权的。
第三、不知道我在copyright有什么不妥，我全部事实说话，从头到尾没有带自己任何情绪。
第四、为什么去fork你的代码？，你可以看看这里面有你多少东西，里面之前有你跟洪舜上传的课程设计的代码，但是洪舜作为我们的学工助理，我就没有删掉那部分的东西。如果你对此有疑问，我已经删掉。

**Comment by ITJesse** [comment]
你明白GPLv2的意思吗

**Comment by ITJesse** [comment]
那么请问。Ubuntu有多少Linux内核的东西呢？是不是就不用fork了？

**Comment by zhoubenbentime** [comment]
首先：如果你说你对你早期的版本和你早期的任何代码拥有封闭版权，无可厚非。如果按照gplv2,"根据GPL v2的相关规定：只要这种修改文本在整体上或者其某个部分来源于遵循GPL的程序，该修改文本的整体就必须按照GPL流通，不仅该修改文本的源码必须向社 会公开，而且对于这种修改文本的流通不准许附加修改者自己作出的限制。"
第二：早期也是由洪舜将你的代码引入我们部门，我们也为此支付了600给洪舜和你，用于服务器托管和使用的权利，最开始你并没有申明你的你的任何权限。
第三：之后由我对系统做了全面的升级，当然也保留的你的少部分交互代码。现在你要声明你的封闭权限，可以。
第四：我们还是非常感谢你早期的付出，在接下来的时间内，我会将早期遗留的代码进行删除。

**Comment by ITJesse** [comment]
请不要再这里使用真名了谢谢，周仙宝同学

**Comment by ITJesse** [comment]
对于第二点，600全部是服务器费用，项目开发属于开源性质，我没有收取任何报酬
还是对于第二点，我的权力我声明在了LICENSE里，但是被你删除了，这个在我仓库的init commit中就有生成
对于你所说的第四点，你知道git仓库可以查看从init开始的历史代码的功能吗？

**Comment by ITJesse** [comment]
在我仓库的init commit中就有生成一个叫做LICENSE的开源协议，声明了我的代码采用GPLv2协议，请仔细研读
https://github.com/ITJesse/HDD

**Comment by zhoubenbentime** [comment]
关于你中文的我已经换掉，至于第二点提到600块用途，洪舜和你和我们，没有在版权做过任何说明，这一点，首先你得明确，我们也并不只知道你早期的版本遵循什么GPlv2协议。对于我们而言，支付600元后，对早期的系统有使用权。之后我们也同样不知道你在init的时候是一个什么协议。知道去年11月份申明了你的版权，我们也在删除你的部分，最后系统也壮大到一定程度，但是还是保留早期少量的交互代码，因为在系统运行的时候，我做很大的改动时候，就改变我们的习惯，所以至今如果你还依然坚持你的版权权利。没有问题，我会尽快删除遗留的部分。

**Comment by zhoubenbentime** [comment]
在早起使用你的代码，是洪舜同学直接给我，不是使用你的仓库的代码。
然后最后再说点，我觉得这样很没有意思，在这个项目本身，我没有获利，没有用作商业用途，纯粹为了业余练习编程使用和学生工作服务，况且最后整个系统我基本上重做了，你的仓库也放到readme上面，你和大家都可以去比较一下。究竟还有多少的东西，属于你，和属于我。你这样一会儿贴吧，一会儿github上说，不知道你是为什么。究竟洪舜怎么传达我的意思。我也不想深究了，没意思。

**Comment by ITJesse** [comment]
你要删，没问题，请删除本仓库，以及你手上现有的侵权代码，并关闭网站，直到你删完为止。
所以非要我这么说吗？我知道你们肯定是不会这么做的，所以这么说出来也没意思。
国人版权意识的薄弱在你这里体现的淋漓尽致。对于开源精神的理解也是有着相当大的偏差。
你一再强调没有获利，没有用作商业用途，纯粹为了业余练习编程使用和学生工作服务，基本上重做，但是依据GPLv2，你现在的行为就是违反了DMCA。
你如果不能从现在开始接受这些，那么请你xxxxx，我就说这么多

**Comment by lincanbin** [comment]
声援，只要你使用了GPL协议的一部分代码，新项目就必须以GPL发布，并且需要带上原协议。

**Comment by zhoubenbentime** [comment]
本来很客气的说话，毕竟大家最开始是算是。。。无语，要不麻烦你们去我的文件看看。。

**Comment by cxshun** [comment]
声援一下，使用了别人代码，该注明啥License还是该注明，程序员圈子很小的，搞坏了名声对自己也没啥好处。
如果不懂什么叫开源协议，可以先去学习一下。

**Comment by zhoubenbentime** [comment]
我在重新说明，如果觉得代码有跟他之前一样，或者使用过他的代码。请亲自去看代码。他的仓库我已经放到下面，请亲自去比对

**Comment by yanwen** [comment]
声援一下，使用了别人代码，该注明啥License还是该注明，程序员圈子很小的，搞坏了名声对自己也没啥好处。
如果不懂什么叫开源协议，可以先去学习一下。

V2EX 观光团路过。。

**Comment by Gaohaoyang** [comment]
baidu-ife观光团路过。。。BootStrap做成这样确实丢人

**Comment by popu125** [comment]
v2观光团路过。。。README.md已经改了哎~

**Comment by uuair** [comment]
如果楼主知道在围观的人群中，有着一堆无论是git还是GPL还是各种license熟的不能再熟的人，楼主会不会紧张？
如果楼主知道，最后的结果不仅仅是一句抱歉或者一句我不知道就能解决的，楼主会不会紧张？
如果楼主想把责任推给临时工，或者那种干脆我来扛的尽头，一点都不优雅。
抄人家的，你写上人家的名字啊，你想当婊子，还要立牌坊，不能够这么多好事都是你做了吧。
开源是一种精神，不是拿来主义，而是奉献，明白不？
你可以光明磊落的抄，fork对方的库又怎么了？
你是怕参加比赛会被人看出来不是原创么？
那你要这种虚名干什么？有名次就有女朋友了？真扯淡
